---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sifu-frontend-config
data:
  API_URI_BASE: http://backend:3333
  AUTH0_REDIRECT_URI_BASE: http://backend:8080
  AUTH0_DOMAIN: dreweaster.eu.auth0.com
  AUTH0_CLIENT_ID: RW3cQ2q2b2t4m4ivaPfggqN6O5sfyg1I
  AUTH0_AUDIENCE: http://my-music-library.com
  AUTH0_REALM: my_music_library
  AUTH0_SCOPE: full_access
  EXIT_ON_PRESSING_ENTER: "false"
  CLUSTER_TYPE: k8s
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sifu-frontend-app
        tier: frontend
    spec:
      containers:
      - name: sifu-front-end
        image: gcr.io/sifu-1/sifu-front-end:v2
        command: ["/scripts/initenvsubst.sh"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: wrapper
          mountPath: /scripts
      volumes:
      - name: wrapper
        configMap:
          name: wrapper
          defaultMode: 0744
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: sifu-frontend-app
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: sifu-frontend-app
    tier: frontend